### PR TITLE
fix remove group (closes #29)

### LINKED ISSUE #29: RemoveGroup don't remove policies relations

### PR DESCRIPTION
**Pull request by gerson24**

### CODE REVIEW

File: database/postgresql/group_test.go [hunk 1]
```diff
@@ -803,13 +826,35 @@ func TestPostgresRepo_RemoveGroup(t *testing.T) {
...
+			continue
+		}
+
+		// Check total group policy relations
+		totalRelations, err = getGroupPolicyRelationCount("", "")
+		if err != nil {
+			t.Errorf("Test %v failed. Unexpected error counting total group policy relations: %v", n, err)
+			continue
+		}
+		if relations != 0 {
```
Comment (rsoletob) [inline database/postgresql/group_test.go]: totalRelations?

File: database/postgresql/group_test.go [hunk 2]
```diff
@@ -803,13 +826,35 @@ func TestPostgresRepo_RemoveGroup(t *testing.T) {
 		// Check total group user relations
 		totalRelations, err := getGroupUserRelations("", "")
 		if err != nil {
-			t.Errorf("Test %v failed. Unexpected error counting total relations: %v", n, err)
+			t.Errorf("Test %v failed. Unexpected error counting total group user relations: %v", n, err)
 			continue
 		}
 		if relations != 0 {
```
Comment (rsoletob) [inline database/postgresql/group_test.go]: totalRelations?
